import express from 'express'
import cors from 'cors'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)

const app = express()
const PORT = process.env.PORT || 3001

app.use(cors())
app.use(express.json())

// Templates API
const templates = [
  {
    id: 1,
    name: 'Simple Token',
    description: 'Basic fungible token implementation',
    category: 'Token',
    code: `module cedraforge::simple_token {
    use std::signer;
    
    struct Token has key {
        supply: u64,
    }
    
    public fun initialize(account: &signer) {
        move_to(account, Token { supply: 0 });
    }
}`,
    rating: 4.5,
    downloads: 234,
    author: 'CedraTeam',
  },
  {
    id: 2,
    name: 'NFT Collection',
    description: 'Complete NFT implementation',
    category: 'NFT',
    code: `module cedraforge::nft {
    use std::signer;
    
    struct NFT has key {
        id: u64,
        owner: address,
    }
    
    public fun mint(account: &signer, id: u64) {
        move_to(account, NFT { id, owner: signer::address_of(account) });
    }
}`,
    rating: 4.8,
    downloads: 189,
    author: 'CedraTeam',
  },
]

// Routes
app.get('/api/templates', (req, res) => {
  res.json(templates)
})

app.get('/api/templates/:id', (req, res) => {
  const template = templates.find((t) => t.id === parseInt(req.params.id))
  if (template) {
    res.json(template)
  } else {
    res.status(404).json({ error: 'Template not found' })
  }
})

app.post('/api/compile', async (req, res) => {
  const { code } = req.body
  
  // Simulate compilation
  // In production, this would call the Move compiler
  setTimeout(() => {
    res.json({
      success: true,
      message: 'Compilation successful',
      warnings: [],
      errors: [],
    })
  }, 1000)
})

app.post('/api/generate-docs', async (req, res) => {
  const { code } = req.body
  
  // Simulate documentation generation
  // In production, this would analyze the Move code and generate docs
  const docs = `# Contract Documentation

## Overview
Auto-generated documentation from Move contract.

## Functions
- Functions extracted from code analysis

## Structs
- Structs and resources identified

Generated by CedraForge Studio
`
  
  res.json({
    success: true,
    documentation: docs,
  })
})

app.post('/api/achievements/unlock', async (req, res) => {
  const { userId, achievementType } = req.body
  
  // In production, this would interact with the Move contract
  res.json({
    success: true,
    achievement: {
      type: achievementType,
      points: 100,
      unlocked: true,
    },
  })
})

app.get('/api/leaderboard', (req, res) => {
  // Mock leaderboard data
  res.json([
    { rank: 1, user: 'Developer1', score: 2500, achievements: 12 },
    { rank: 2, user: 'Developer2', score: 2000, achievements: 10 },
    { rank: 3, user: 'Developer3', score: 1800, achievements: 9 },
    { rank: 4, user: 'Developer4', score: 1500, achievements: 8 },
    { rank: 5, user: 'Developer5', score: 1200, achievements: 7 },
  ])
})

app.listen(PORT, () => {
  console.log(`🚀 CedraForge Studio Backend running on port ${PORT}`)
})

